/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Fredi
 */
public class Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnticket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnregistrarna = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnregistrara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltitulo.setText("ENTRADA");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fredi\\Downloads\\barra.jpg")); // NOI18N

        txtnticket.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ticket");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID");

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NO ABONADO");

        btnregistrarna.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnregistrarna.setForeground(new java.awt.Color(0, 0, 102));
        btnregistrarna.setText("Registrar");
        btnregistrarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarnaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ABONADO");

        btnregistrara.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnregistrara.setForeground(new java.awt.Color(0, 0, 102));
        btnregistrara.setText("Registrar");
        btnregistrara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistraraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnregistrara)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(txtnticket, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnregistrarna)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lbltitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistrarna)
                    .addComponent(btnregistrara))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarnaActionPerformed
        // TODO add your handling code here:
        Random rand = new Random(); 
        
        int x = rand.nextInt(99999);
        txtnticket.setText(Integer.toString(x));
        
        try{ 
        ConectarBD conexion = new ConectarBD();          
              
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long fecha = utilDate.getTime();
        java.sql.Timestamp sqlTimestamp = new java.sql.Timestamp(fecha);
      
        System.out.println("sql.Timestamp: " + sqlTimestamp);
        
        String instruccion = "insert into controlnoabonado (n_ticket,fecha_ingreso,fecha_salida,valor,estado)values (?,?,?,?,?)";
        int valor=0;
        conexion.sentencia = conexion.getConexion().prepareStatement(instruccion);
        conexion.sentencia.setInt(1, x);
        conexion.sentencia.setTimestamp(2,  sqlTimestamp);
        conexion.sentencia.setTimestamp(3,  null);
        conexion.sentencia.setInt(4,  valor);
        conexion.sentencia.setString(5,  "debe");
        conexion.sentencia.execute();

        JOptionPane.showMessageDialog(null, "ABRIR BARRA DE ENTRADA  TICKET #  "+  x, "AUTORIZADO", JOptionPane.INFORMATION_MESSAGE);
        btnregistrarna.setEnabled(false);
        this.dispose();
        new Entrada().setVisible(true);
        
        }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error SQL"+e, "Informacion", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnregistrarnaActionPerformed

    private void btnregistraraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistraraActionPerformed
        // TODO add your handling code here:
          try{
            if ((txtid.getText().trim().length() == 0)) 
                JOptionPane.showMessageDialog(null, "PASE SU TARJETA", "ERROR", JOptionPane.ERROR_MESSAGE);
            else{
            String criterio=txtid.getText();
            int num = Integer.parseInt(criterio);
            ConectarBD conexion= new ConectarBD();
            
            Statement consulta1;
            consulta1=conexion.getConexion().createStatement();
            ResultSet resultado1 = consulta1.executeQuery("select estado from controlabonado where id_abonado=" + criterio + "");
                   
            while(resultado1.next())
            {
            if(resultado1.isLast())
                {
                int estado= resultado1.getInt("estado");
                System.out.println(estado);
            
                    if (estado == 0) 
                        {
                        Statement consulta;
                        consulta=conexion.getConexion().createStatement();
                        ResultSet resultado = consulta.executeQuery("select * from abonado where id_abonado=" + criterio + "");
            
                        while (resultado.next()) 
                            {
                                                                          
                         java.util.Date utilDate = new java.util.Date(); //fecha actual
                         long lnMilisegundos = utilDate.getTime();
                         java.sql.Timestamp sqlTimestamp = new java.sql.Timestamp(lnMilisegundos);
                         System.out.println("sql.Timestamp: " + sqlTimestamp);

                         String instruccion = "insert into controlabonado (id_abonado,fecha_ingreso,fecha_salida,estado)values (?,?,?,?)";
                         int valor=1;
                         conexion.sentencia = conexion.getConexion().prepareStatement(instruccion);
                         conexion.sentencia.setInt(1, num);
                         conexion.sentencia.setTimestamp(2, sqlTimestamp);
                         conexion.sentencia.setTimestamp(3, null);
                         conexion.sentencia.setInt(4, valor);
                         conexion.sentencia.execute();

                         JOptionPane.showMessageDialog(null, "ABRIR BARRA DE ENTRADA ABONADO # " +num, "AUTORIZADO", JOptionPane.INFORMATION_MESSAGE);
                         btnregistrara.setEnabled(false);
                         txtid.setEditable(false);
                            }
                        resultado.close();           
                        }
                    else
                         JOptionPane.showMessageDialog(null, "YA ESTA DENTRO", "NO AUTORIZADO", JOptionPane.INFORMATION_MESSAGE);
            
                }
            
            }
            
                     resultado1.close();
                     conexion.getConexion().close();
                     this.dispose();
                     new Entrada().setVisible(true);
            //}
                     //else
                     //JOptionPane.showMessageDialog(this, "Usted No se encuentra registrado", "Informacion", JOptionPane.ERROR_MESSAGE);
                 
             }
            }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error"+e, "Informacion", JOptionPane.ERROR_MESSAGE);
            }
          
       
    }//GEN-LAST:event_btnregistraraActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();
        if (txtid.getText().length() >= 8) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO PUEDE INGRESAR NUMEROS", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtidKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrara;
    private javax.swing.JButton btnregistrarna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnticket;
    // End of variables declaration//GEN-END:variables
}
